kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: username2
  namespace: ns-cloudops
subjects:
- kind: User
  name: sharmila.tarra@dxc.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io